/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glucolisis;

/**
 *
 * @author 18PROGB0115
 */
public class Cuestionario extends javax.swing.JFrame {

    /**
     * Creates new form Cuestionario
     */
    public Cuestionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTitulo = new javax.swing.JTextArea();
        btnAyuda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPreguno = new javax.swing.JTextArea();
        rbOpcapreguno = new javax.swing.JRadioButton();
        rbOpcbpreguno = new javax.swing.JRadioButton();
        rbOpccprguno = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPregdos = new javax.swing.JTextArea();
        rbOpcapregdos = new javax.swing.JRadioButton();
        rbOpcbpregdos = new javax.swing.JRadioButton();
        rbOpccpregdos = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtPregtres = new javax.swing.JTextArea();
        rbOpcapregtres = new javax.swing.JRadioButton();
        rbOpccpregtres = new javax.swing.JRadioButton();
        rbOpcbpregtres = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPregcuatro = new javax.swing.JTextArea();
        rbOpcapregcuatro = new javax.swing.JRadioButton();
        rbOpcbpregcuatro = new javax.swing.JRadioButton();
        rbOpccpregcuatro = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPregcinco = new javax.swing.JTextArea();
        rbOpcapregcinco = new javax.swing.JRadioButton();
        rbOpccpregcinco = new javax.swing.JRadioButton();
        rbOpcbpregcinco = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("FrmCuestionario"); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtTitulo.setColumns(20);
        txtTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtTitulo.setRows(5);
        txtTitulo.setText("                      Cuestionario");
        jScrollPane1.setViewportView(txtTitulo);

        btnAyuda.setText("?");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPreguno.setEditable(false);
        txtPreguno.setColumns(20);
        txtPreguno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPreguno.setRows(5);
        txtPreguno.setText("¿En qué organelo se\nlleva a cabo la \nglucolisis?");
        jScrollPane2.setViewportView(txtPreguno);

        rbOpcapreguno.setText("En el citoplasma");
        rbOpcapreguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcapregunoActionPerformed(evt);
            }
        });

        rbOpcbpreguno.setText("En el citosol");

        rbOpccprguno.setText("En la célula");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPregdos.setEditable(false);
        txtPregdos.setColumns(20);
        txtPregdos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPregdos.setRows(5);
        txtPregdos.setText("¿En qué ciclo se \ngenera el piruvato?");
        jScrollPane3.setViewportView(txtPregdos);

        rbOpcapregdos.setText("En el ciclo de calvin");

        rbOpcbpregdos.setText("En la fase oscura");

        rbOpccpregdos.setText("En el cliclo de Krebs");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPregtres.setEditable(false);
        txtPregtres.setColumns(20);
        txtPregtres.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPregtres.setLineWrap(true);
        txtPregtres.setRows(5);
        txtPregtres.setText("¿En qué condición se da la respiración aeróbica?");
        txtPregtres.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtPregtres);

        rbOpcapregtres.setText("En la presencia de oxígeno");
        rbOpcapregtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOpcapregtresActionPerformed(evt);
            }
        });

        rbOpccpregtres.setText("Cuando se obtiene el piruvato");

        rbOpcbpregtres.setText("En la ausencia de oxígeno");

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPregcuatro.setEditable(false);
        txtPregcuatro.setColumns(20);
        txtPregcuatro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPregcuatro.setLineWrap(true);
        txtPregcuatro.setRows(5);
        txtPregcuatro.setText("¿En qué condición se da la fermentación?");
        txtPregcuatro.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtPregcuatro);

        rbOpcapregcuatro.setText("En la segunda fase");

        rbOpcbpregcuatro.setText("En la obtención de glucosa");

        rbOpccpregcuatro.setText("En ausencia de oxígeno");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtPregcinco.setEditable(false);
        txtPregcinco.setColumns(20);
        txtPregcinco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPregcinco.setLineWrap(true);
        txtPregcinco.setRows(5);
        txtPregcinco.setText("¿En qué consiste la glucólisis?");
        txtPregcinco.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtPregcinco);

        rbOpcapregcinco.setText("En la creación de ADN");

        rbOpccpregcinco.setText("En oxidar glucosa para obtener energía");

        rbOpcbpregcinco.setText("En la respiración celular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAyuda)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOpccpregcuatro)
                    .addComponent(rbOpccpregcinco)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rbOpcapregcinco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbOpcbpregcinco))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbOpccpregdos)
                                .addComponent(rbOpcapregdos)
                                .addComponent(rbOpccprguno)
                                .addComponent(rbOpcapreguno)
                                .addComponent(rbOpcapregtres)
                                .addComponent(rbOpccpregtres)
                                .addComponent(rbOpcapregcuatro))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbOpcbpregcuatro)
                                .addComponent(rbOpcbpregtres)
                                .addComponent(rbOpcbpreguno)
                                .addComponent(rbOpcbpregdos)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnAyuda)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbOpcapreguno)
                            .addComponent(rbOpcbpreguno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOpccprguno))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbOpcapregdos)
                            .addComponent(rbOpcbpregdos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(rbOpccpregdos))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(rbOpcbpregtres))
                            .addComponent(rbOpcapregtres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbOpccpregtres))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rbOpcbpregcuatro))
                            .addComponent(rbOpcapregcuatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbOpccpregcuatro))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbOpcapregcinco)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(rbOpcbpregcinco)))
                        .addGap(18, 18, 18)
                        .addComponent(rbOpccpregcinco)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOpcapregtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcapregtresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcapregtresActionPerformed

    private void rbOpcapregunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOpcapregunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOpcapregunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JRadioButton rbOpcapregcinco;
    private javax.swing.JRadioButton rbOpcapregcuatro;
    private javax.swing.JRadioButton rbOpcapregdos;
    private javax.swing.JRadioButton rbOpcapregtres;
    private javax.swing.JRadioButton rbOpcapreguno;
    private javax.swing.JRadioButton rbOpcbpregcinco;
    private javax.swing.JRadioButton rbOpcbpregcuatro;
    private javax.swing.JRadioButton rbOpcbpregdos;
    private javax.swing.JRadioButton rbOpcbpregtres;
    private javax.swing.JRadioButton rbOpcbpreguno;
    private javax.swing.JRadioButton rbOpccpregcinco;
    private javax.swing.JRadioButton rbOpccpregcuatro;
    private javax.swing.JRadioButton rbOpccpregdos;
    private javax.swing.JRadioButton rbOpccpregtres;
    private javax.swing.JRadioButton rbOpccprguno;
    private javax.swing.JTextArea txtPregcinco;
    private javax.swing.JTextArea txtPregcuatro;
    private javax.swing.JTextArea txtPregdos;
    private javax.swing.JTextArea txtPregtres;
    private javax.swing.JTextArea txtPreguno;
    private javax.swing.JTextArea txtTitulo;
    // End of variables declaration//GEN-END:variables
}
